window.AppState = {
  screens: {
    mainMenu: null,
    singleMenu: null,
    onlineMenu: null,
    findPopup: null,
    createWorldPopup: null,
    gameScreen: null,
  },
  menu: {
    servers: [],
    logoTime: 0,
    serverList: {
      selectedIndex: -1,
      rowHeight: 50,
      scrollY: 0,
      draggingThumb: false,
      dragStartY: 0,
      dragStartScrollY: 0,
    },
    singleWorldList: {
      selectedWorldId: null,
      worlds: [],
      filter: '',
      rowHeight: 96,
      scrollY: 0,
      draggingThumb: false,
      dragStartY: 0,
      dragStartScrollY: 0,
    },
  },
  game: {
    running: false,
    started: false,
    lastTime: 0,
    mode: 'single',
    currentWorldId: null,
    currentWorldName: '',
    spawnX: 0,
    spawnY: 0,
  },
  inventory: {
    open: false,
    columns: 5,
    rows: 4,
    totalSlots: 20,
    craftScroll: 0,
    selectedHotbarSlot: 0,
    hoveredSlot: -1,
    draggedSlot: -1,
    draggedItem: null,
    slots: Array.from({ length: 20 }, () => null),
  },
  mining: {
    targetKey: '',
    targetType: '',
    targetX: 0,
    targetY: 0,
    progress: 0,
    frame: 0,
    particleTimer: 0,
    maxReachTiles: 5.2,
  },
  combat: {
    maxHealth: 5,
    health: 5,
    dead: false,
    hurtFlashTimer: 0,
    hurtFlashDuration: 18,
    fallStartY: 0,
    falling: false,
    fallDamageThreshold: 11.5,
  },
  entities: {
    drops: [],
    particles: [],
    gibs: [],
  },
  debug: {
    panelOpen: false,
    showHitbox: false,
  },
  chat: {
    open: false,
    input: '',
    messages: [],
    maxMessages: 24,
    fadeDelay: 7000,
    fadeDuration: 2000,
  },
  input: {
    left: false,
    right: false,
    jump: false,
    inventoryTogglePressed: false,
    zoomHeld: false,
    sprint: {
      active: false,
      direction: 0,
      doubleTapWindow: 260,
      lastLeftTapAt: 0,
      lastRightTapAt: 0,
    },
  },
  mouse: {
    x: 0,
    y: 0,
    leftDown: false,
    rightDown: false,
  },
};
